## Pandas Library

In [1]:
import numpy as np

In [2]:
array_2d = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [3]:
print(array_2d)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [4]:
reshape_array = array_2d.reshape(10, 2)

In [5]:
print(reshape_array)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [6]:
print(reshape_array%2)

[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]


In [7]:
print("Sum:", np.sum(array_2d))

Sum: 210


In [8]:
difference = array_2d - 2
print(difference)

[[-1  0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17 18]]


In [9]:
print("Product:", np.prod(array_2d))

Product: -2102132736


In [10]:
division = array_2d / 2
print(division)

[[ 0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5. ]
 [ 5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10. ]]


## Numpy Library

In [11]:
import pandas as pd

In [12]:
data = {
    "Name": ["Akarsh", "Ajit", "Bishal", "Vishal"],
    "Age": [23, 33, 43, 53],
    "Score": [87, 90, 73, None]
}

In [13]:
df = pd.DataFrame(data)

In [14]:
print("DataFrame:\n", df)

DataFrame:
      Name  Age  Score
0  Akarsh   23   87.0
1    Ajit   33   90.0
2  Bishal   43   73.0
3  Vishal   53    NaN


In [15]:
print("Mean Score:", df["Score"].median())

Mean Score: 87.0


In [16]:
df["Score"] = df["Score"].fillna(df["Score"].median())
print("Cleaned data:\n", df)

Cleaned data:
      Name  Age  Score
0  Akarsh   23   87.0
1    Ajit   33   90.0
2  Bishal   43   73.0
3  Vishal   53   87.0


## Statistics Library

In [17]:
import statistics as stat

# Sample data
points = [53, 90, 89, 27, 45, 39, 100]

In [18]:
print("Mean:", stat.mean(points))
print("Median:", stat.median(points))
print("Variance:", stat.variance(points))
print("Standard Deviation:", stat.stdev(points))

Mean: 63.285714285714285
Median: 53
Variance: 844.9047619047619
Standard Deviation: 29.06724551629827
